name: Install Skopeo
description: Install Skopeo from source on ubuntu runner

inputs:
  version:
    description: The Skopeo version to install
    default: v1.14.3
    required: false
  repo:
    description: The Skopeo repository
    default: github.com/containers/skopeo
    required: false

outputs:
  result:
    description: Did the installation succeed?
    value: ${{ steps.result.outputs.result == 0 && true || false }}

runs:
  using: composite
  steps:

    - name: Install Skopeo
      id: result
      run: |
          sudo apt-get -y update
          sudo apt install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config go-md2man
          sudo mkdir -p $GOPATH/src/${{ inputs.repo }}
          sudo git clone --depth 1 -b ${{ inputs.version }} https://${{ inputs.repo }} $GOPATH/src/${{ inputs.repo }}
          pushd $GOPATH/src/${{ inputs.repo }} && sudo make install
          popd
          skopeo --version
          echo "result=$?" >> $GITHUB_OUTPUT
      shell: bash
